//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.25 at 08:21:22 PM CET 
//

package lasergame;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Data;

/**
 * <p>
 * Java class for Joueur complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Joueur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroJoueur" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pseudo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="couleur" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="score" type="{http://www.example.org/lasergame}Score"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Joueur", propOrder = { "numeroJoueur", "pseudo", "couleur",
		"score" })
public @Data class Joueur {

	protected int numeroJoueur;
	@XmlElement(required = true)
	protected String pseudo;
	@XmlElement(required = true)
	protected String couleur;
	@XmlElement(required = true)
	protected Score score;
	
	
	/* 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return " \n \t - Joueur [ \n \t\t - numeroJoueur=" + numeroJoueur + ", \n \t\t - pseudo=" + pseudo
				+ ", \n \t\t - couleur=" + couleur + ", \n \t\t - score=" + score + "]";
	}	
}
