//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.25 at 08:21:22 PM CET 
//

package lasergame;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Data;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroPartie" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="libellePartie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Joueurs" type="{http://www.example.org/lasergame}Joueur" maxOccurs="unbounded"/>
 *         &lt;element name="Scores" type="{http://www.example.org/lasergame}Score"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "numeroPartie", "libellePartie", "joueurs",
		"scores" })
@XmlRootElement(name = "Partie")
public @Data class Partie {

	protected int numeroPartie;
	@XmlElement(required = true)
	protected String libellePartie;
	@XmlElement(name = "Joueurs", required = true)
	protected List<Joueur> joueurs;
	@XmlElement(name = "Scores", required = true)
	protected Score scores;

	/*
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Partie [ \n - numeroPartie=" + numeroPartie
				+ ", \n - libellePartie=" + libellePartie
				+ ", \n - joueurs=" + joueurs + ", \n - scores=" + scores
				+ "]";
	}
}
