//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.25 at 08:21:22 PM CET 
//

package lasergame;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import lombok.Data;

/**
 * <p>
 * Java class for Score complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Score">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nbreMorts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nbreTues" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="handicap" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Score", propOrder = { "numeroScore", "nbreMorts", "nbreTues",
		"handicap" })
public @Data class Score {

	protected int numeroScore;
	protected int nbreMorts;
	protected int nbreTues;
	protected double handicap;
	
	/* 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Score [numeroScore=" + numeroScore + ", nbreMorts=" + nbreMorts
				+ ", nbreTues=" + nbreTues + ", handicap=" + handicap + "]";
	}
}
